/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as CreatorsHandleRouteImport } from './routes/creators.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsHandleRoute = CreatorsHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => CreatorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/trending': typeof TrendingRoute
  '/creators/$handle': typeof CreatorsHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/trending': typeof TrendingRoute
  '/creators/$handle': typeof CreatorsHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/trending': typeof TrendingRoute
  '/creators/$handle': typeof CreatorsHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/creators' | '/trending' | '/creators/$handle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/creators' | '/trending' | '/creators/$handle'
  id: '__root__' | '/' | '/creators' | '/trending' | '/creators/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatorsRoute: typeof CreatorsRouteWithChildren
  TrendingRoute: typeof TrendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$handle': {
      id: '/creators/$handle'
      path: '/$handle'
      fullPath: '/creators/$handle'
      preLoaderRoute: typeof CreatorsHandleRouteImport
      parentRoute: typeof CreatorsRoute
    }
  }
}

interface CreatorsRouteChildren {
  CreatorsHandleRoute: typeof CreatorsHandleRoute
}

const CreatorsRouteChildren: CreatorsRouteChildren = {
  CreatorsHandleRoute: CreatorsHandleRoute,
}

const CreatorsRouteWithChildren = CreatorsRoute._addFileChildren(
  CreatorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorsRoute: CreatorsRouteWithChildren,
  TrendingRoute: TrendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
