/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
<<<<<<< HEAD
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as TermsRouteImport } from './routes/terms'
=======
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubmitRouteImport } from './routes/submit'
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as CreatorsHandleRouteImport } from './routes/creators.$handle'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsHandleRoute = CreatorsHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => CreatorsRoute,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
<<<<<<< HEAD
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
=======
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
  '/trending': typeof TrendingRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/post/$postId': typeof PostPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
<<<<<<< HEAD
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
=======
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
  '/trending': typeof TrendingRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/post/$postId': typeof PostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
<<<<<<< HEAD
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
=======
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
  '/trending': typeof TrendingRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/post/$postId': typeof PostPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/creators'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
<<<<<<< HEAD
    | '/privacy'
    | '/search'
    | '/signup'
    | '/submit'
    | '/terms'
=======
    | '/search'
    | '/signup'
    | '/submit'
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
    | '/trending'
    | '/creators/$handle'
    | '/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/creators'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
<<<<<<< HEAD
    | '/privacy'
    | '/search'
    | '/signup'
    | '/submit'
    | '/terms'
=======
    | '/search'
    | '/signup'
    | '/submit'
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
    | '/trending'
    | '/creators/$handle'
    | '/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/creators'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
<<<<<<< HEAD
    | '/privacy'
    | '/search'
    | '/signup'
    | '/submit'
    | '/terms'
=======
    | '/search'
    | '/signup'
    | '/submit'
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
    | '/trending'
    | '/creators/$handle'
    | '/post/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreatorsRoute: typeof CreatorsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
<<<<<<< HEAD
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
=======
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SubmitRoute: typeof SubmitRoute
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
  TrendingRoute: typeof TrendingRoute
  PostPostIdRoute: typeof PostPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$handle': {
      id: '/creators/$handle'
      path: '/$handle'
      fullPath: '/creators/$handle'
      preLoaderRoute: typeof CreatorsHandleRouteImport
      parentRoute: typeof CreatorsRoute
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CreatorsRouteChildren {
  CreatorsHandleRoute: typeof CreatorsHandleRoute
}

const CreatorsRouteChildren: CreatorsRouteChildren = {
  CreatorsHandleRoute: CreatorsHandleRoute,
}

const CreatorsRouteWithChildren = CreatorsRoute._addFileChildren(
  CreatorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreatorsRoute: CreatorsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
<<<<<<< HEAD
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
=======
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SubmitRoute: SubmitRoute,
>>>>>>> 0d4ec58c09a4d3d2f04725b8a3fae466d037dd0c
  TrendingRoute: TrendingRoute,
  PostPostIdRoute: PostPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
